x-service-template: &service-template
  build:
    context: .
    dockerfile: Dockerfile
  env_file:
    - .env
  environment:
    - NODE_ENV=${NODE_ENV}
    - LOG_LEVEL=${LOG_LEVEL}
    - RABBITMQ_HOST=${RABBITMQ_HOST}
    - RABBITMQ_PORT=${RABBITMQ_PORT}
    - RABBITMQ_USER=${RABBITMQ_USER}
    - RABBITMQ_PASSWORD=${RABBITMQ_PASSWORD}
  volumes:
    - ./:/app
  depends_on:
    rabbitmq:
      condition: service_healthy

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s

  mongo:
    image: mongo:6
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=collector
    command: ["mongod", "--quiet"]
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 5s
      timeout: 5s
      retries: 5

  producer:
    <<: *service-template
    command: ["pnpm", "start", "--filter", "./services/producer"]
    container_name: producer
    ports:
      - "${PORT}:${PORT}"

  worker:
    <<: *service-template
    command: ["pnpm", "start", "--filter", "./services/worker"]
    container_name: worker

  collector:
    <<: *service-template
    command: ["pnpm", "start", "--filter", "./services/collector"]
    container_name: collector
    environment:
      - NODE_ENV=${NODE_ENV}
      - LOG_LEVEL=${LOG_LEVEL}
      - RABBITMQ_HOST=${RABBITMQ_HOST}
      - RABBITMQ_PORT=${RABBITMQ_PORT}
      - RABBITMQ_USER=${RABBITMQ_USER}
      - RABBITMQ_PASSWORD=${RABBITMQ_PASSWORD}
      - MONGO_URI=${MONGO_URI}
    depends_on:
      rabbitmq:
        condition: service_healthy
      mongo:
        condition: service_healthy

volumes:
  mongo_data:
